// Copyright 2014-2020 VintaSoft Ltd. All rights reserved.
// This software is protected by International copyright laws.
// Any copying, duplication, deployment, redistribution, modification or other
// disposition hereof is STRICTLY PROHIBITED without an express written license
// granted by VintaSoft Ltd. This notice may not be removed or otherwise
// altered under any circumstances.
// This code may NOT be used apart of the VintaSoft product.
var Vintasoft;
(function(q){void 0==q.usedJavaScriptEngine&&(q.usedJavaScriptEngine=1);if(1==q.usedJavaScriptEngine&&void 0==window.jQuery)throw Error("jQuery is not found.");if(void 0==q.version)q.version="1.7.0.3";else if("1.7.0.3"!==q.version)throw Error("Wrong script version.");q.Shared=q.Shared||(q.Shared={});(function(n){function V(b){function c(){}c.prototype=b;return new c}Array.isArray||(Array.isArray=function(b){return"[object Array]"===Object.prototype.toString.call(b)});Array.prototype.indexOf||(Array.prototype.indexOf=
function(b,c){var e;if(null==this)throw new TypeError("'this' is null or not defined");var g=Object(this),l=g.length>>>0;if(0===l)return-1;e=+c||0;Infinity===Math.abs(e)&&(e=0);if(e>=l)return-1;for(e=Math.max(0<=e?e:l-Math.abs(e),0);e<l;){if(e in g&&g[e]===b)return e;e++}return-1});Math.trunc||(Math.trunc=function(b){b=+b;return b-b%1||(isFinite(b)&&0!==b?0>b?-0:0:b)});n.extend=function(b,c){b.prototype=V(c.prototype);b.prototype.constructor=b;b.superclass=c.prototype};n.cloneObject=function(b){var c=
{},e={},g;for(g in c)Object.prototype.hasOwnProperty.call(c,g)&&(e[g]=c[g]);for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e[g]=b[g]);return e};n.triggerEvent=function(c,d,e){if(0==q.usedJavaScriptEngine){if(c=c[d+"_els"],void 0!==c&&Array.isArray(c))for(d=0;d<c.length;d++)if(void 0==e)c[d]();else c[d](e)}else 1==q.usedJavaScriptEngine&&(void 0==e?$(c).triggerHandler(d):$(c).triggerHandler(d,e))};n.subscribeToEvent=function(c,d,e){if(0==q.usedJavaScriptEngine)d+="_els",void 0==c[d]&&(c[d]=
[]),c[d].push(e);else if(1==q.usedJavaScriptEngine)$(c).on(d,e)};n.unsubscribeFromEvent=function(c,d){0==q.usedJavaScriptEngine?c[d+"_els"]=void 0:1==q.usedJavaScriptEngine&&$(c).off(d)};n.getParents=function(c,d){if(0==q.usedJavaScriptEngine){for(var e=[],g=c&&c.parentElement;g;g=g.parentElement)e.push(g);return e}if(1==q.usedJavaScriptEngine)return $(c).parents(d)};var c=function(){};c.te=function(c){throw Error(c);};c.tae=function(){c.te("Argument type exception.")};c.toe=function(){c.te("Argument out of range exception.")};
c.tne=function(){c.te("Not implemented exception.")};c.tie=function(){c.te("Invalid operation exception.")};c.tof=function(c,d){return typeof c===d};c.iss=function(b){return c.tof(b,"string")};c.isn=function(b){return c.tof(b,"number")};c.isb=function(b){return c.tof(b,"boolean")};c._422=function(b){return c.tof(b,"object")};c.isf=function(b){return c.tof(b,"function")};c.n=function(){for(var b=0;b<arguments.length;b++){var d=arguments[b];c.isn(d)&&!isNaN(d)||c.tae()}};c.b=function(){for(var b=0;b<
arguments.length;b++)c.isb(arguments[b])||c.tae()};c.d=function(b){c.ic(b,Date)||(b=Date.parse(b),isNaN(b)&&c.tae(),b=new Date(b));return b};c.s=function(){for(var b=0;b<arguments.length;b++)c.iss(arguments[b])||c.tae()};c.sz=function(){for(var b=0;b<arguments.length;b++){var d=arguments[b];c.n(d.width);c.n(d.height)}};c.p=function(){for(var b=0;b<arguments.length;b++){var d=arguments[b];c.n(d.x);c.n(d.y)}};c.r=function(){for(var b=0;b<arguments.length;b++){var d=arguments[b];c.p(d);c.sz(d)}};c.e=
function(b,d){var e=c.ic(b,F)?b.valueOf():b;return new d(e)};c.ic=function(c,d){return c instanceof d};c.c=function(b,d,e){c.ic(b,d)||(null!=e?c.te(e):c.tae())};c.ad=function(b,d){Array.isArray(b)||c.tae();if(null!=d)for(var e=0;e<b.length;e++)d(b[e])};c.ac=function(b,d){c.ad(b,function(b){c.c(b,d)})};c.f=function(b,d){c.isf(b)||(null!=d?c.te(d):c.tae())};var F=function(){var c=F.prototype;c.getAllAvailableNames=function(){};c.getAllAvailableValues=function(){};c.valueOf=function(){};c.toString=function(){};
c.equals=function(c){};c.isFlagged=function(){return!1}},L=function(){var c=L.prototype;c.toArray=function(){};c.contains=function(c){};c.add=function(c){};c.remove=function(c){};c.isFlagged=function(){return!0}};n.extend(L,F);var G=function(){};G.create=function(b,d){function e(k,c){var h=[];if(null!=f[c])h.push(f[c]);else for(var p=1;p<=a;)0!==l(c,p)&&h.push(f[p]),p*=2;return h.join("|")}function g(a){return{low:a%4294967296|0,high:a/4294967296|0}}function l(a,c){var k=g(a),h=g(c);return 4294967296*
(k.high&h.high)+((k.low&h.low)>>>0)}for(var f={},a=0,k=0;k<b.length;k++){var p=b[k],m,A;if(c.iss(p.name)&&c.isn(p.value))m=p.value,A=p.name;else for(var h in p){c.iss(h)?(A=h,m=p[h]):c.isn(h)&&(m=h,A=p[h]);break}c.isn(m)&&c.iss(A)||c.te("Enum item must be an object with string name and numeric value.");f[A]=m;f[m]=A}Object.freeze&&Object.freeze(f);if(d)for(k in f)isNaN(+k)||(p=parseInt(k),0!==p&&0===l(p,p-1)&&(a+=p));else for(k in f)isNaN(+k)||(p=parseInt(k),p>a&&(a=p));var w=function(k){if(c.iss(k)){var h=
+k;if(isNaN(h))if(null==f[k]){h=0;k=k.split("|");for(var p=0;p<k.length;p++)h+=f[k[p]];k=h}else k=f[k];else k=h}k>a&&c.tae();h=f[k];null==h&&d&&(h=e(this,k));null!=h&&""!==h||c.tae();this[this[h]=+k]=h};d?n.extend(w,L):n.extend(w,F);k=w.prototype;k.getAllAvailableNames=function(){var a=[],k;for(k in f)isNaN(+k)&&a.push(k);return a};k.getAllAvailableValues=function(){var a=[],k;for(k in f)isNaN(+k)&&null!=f[k]&&a.push(f[k]);return a};k.valueOf=function(){for(var a in this){var k=+a;if(!isNaN(k))return k}};
k.toString=function(){return e(this,this.valueOf())};d&&(k.toArray=function(){var k=this.valueOf(),c=[];if(0===k&&null!=f[k])c.push(new w(0));else for(var h=1;h<=a;){if(0!==l(k,h))try{c.push(new w(h))}catch(p){}h*=2}return c},k.contains=function(a){var k=this.valueOf();c.iss(a)&&(a=f[a]);return l(k,a)===a+0},k.add=function(a){var k=this.valueOf();c.iss(a)&&(a=f[a]);k=g(k);a=g(a);return new w(4294967296*(k.high|a.high)+((k.low|a.low)>>>0))},k.remove=function(a){var k=this.valueOf();c.iss(a)&&(a=f[a]);
var h=a;a=g(k);h=g(h);return new w(l(4294967296*(a.high^h.high)+((a.low^h.low)>>>0),k))});k.equals=function(a){var k=this.valueOf();c.iss(a)&&(a=f[a]);return k===a+0};k.isFlagged=function(){return d};return w};var Q=G.create([{Undefined:0},{Indexed1:1},{BlackWhite:2},{Indexed4:4},{Indexed8:8},{Gray8:9},{Bgr555:14},{Bgr565:15},{Gray16:16},{Bgr24:24},{Bgr32:32},{Bgra32:33},{Bgr48:48},{Bgra64:64}],!1),I=G.create([{Default:0},{Low:1},{High:2},{Bilinear:3},{Bicubic:4},{NearestNeighbor:5},{HighQualityBilinear:6},
{HighQualityBicubic:7}],!1),J=G.create([{Default:0},{HighSpeed:1},{HighQuality:2},{None:3},{AntiAlias:4}],!1),E=G.create([{Url:1},{Base64:2}],!1),u=function(){};u._394=null;u.get_SessionId=function(){return u._394};u.set_SessionId=function(b){null!=u._394&&c.te("Session ID already initialized.");/^[\w,-]+$/.test(b)||c.te("Unsupported Session ID format: ID can contain only latin letters, numbers, '_' and '-' symbols.");u._394=b};u.get_ScrollSize=function(c){null==c&&(c=document.body);var d=document.createElement("div");
c.appendChild(d);d.style.overflow="scroll";d.style.visibility="hidden";d.style.position="absolute";d.style.width="100px";d.style.height="100px";var e=d.offsetWidth-d.clientWidth;0>e&&(e=100-d.clientWidth);c.removeChild(d);return e};u.getScreenDpi=function(){var c=document.createElement("div");document.body.appendChild(c);c.style.position="absolute";c.style.top="-100%";c.style.left="-100%";c.style.width="1in";c.style.height="1in";var d={dpiX:c.offsetWidth,dpiY:c.offsetHeight};document.body.removeChild(c);
return d};u.guid=function(){function c(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return c()+c()+"-"+c()+"-"+c()+"-"+c()+"-"+c()+c()+c()};var D=function(c,d,e,g,l){var f=D.prototype;f.get_ShortName=function(){return this._266};f.get_FullName=function(){return this._105};f.get_Value=function(){return this._277};f.get_ReadOnly=function(){return this._352};f.get_Items=function(){return this._183};f.get_RefreshFromParent=function(){return this._548};this._266=c;this._105=d;
this._277=e;this._352=g;this._183=[];this._548=l?l:!1},R=function(b,d,e,g){function l(a,k){a._277=k._277;a._105=k._105;a._266=k._266;a._352=k._352;a._548=k._548;for(var c=0;c<a._183.length;c++)l(a._183[c],k._183[c])}function f(a,k){for(;a._183.length>k._183.length;)a._183.splice(a._183.length-1,1);for(;a._183.length<k._183.length;)a._183[a._183.length]=k._183[a._183.length];for(var c=0;c<a._183.length;c++)f(a._183[c],k._183[c])}function a(a,k,c){if(a["set_"+k])a["set_"+k](c);else null!=a[k]&&(a[k]=
c)}function k(a,h,p,m){if(c._422(h)){var f=[],b;for(b in h)(null==m?0:-1!==m.indexOf(b))||f.push(b);f.sort();for(b=0;b<f.length;b++){var d=f[b],e="";if(0===d.lastIndexOf("get_",0)&&c.isf(h[d])){var e=d.split("_")[1],l=!0;null!=h["set_"+e]&&c.isf(h["set_"+e])&&(l=!1);var g;try{g=h[d]()}catch(n){g=null}if(null!=g)if(c._422(g))c.ic(g,HTMLElement)||(q=""!==p?p+"_"+e:e,e=new D(e,q,g,l),a.get_Items().push(e),k(e,g,q,m));else if(!c.isf(g)){var q=""!==p?p+"_"+e:e,e=new D(e,q,g,l);a.get_Items().push(e)}}}if(0===
a._183.length&&c._422(h)){b=!0;for(d in h)if(c.isf(h[d])){b=!1;break}d=Object.getOwnPropertyNames(h);g=Array.isArray(h);if(b&&!g)for(b=0;b<d.length;b++)"_"!==d[b][0]&&(q=""!==p?p+"_"+d[b]:d[b],g=h[d[b]],null!=g&&(c._422(g)?(e=new D(d[b],q,g,!1,!0),a.get_Items().push(e),k(e,g,q,m)):(e=new D(d[b],q,g,!1,!0),a.get_Items().push(e))));else if(g)for(p=a.get_FullName(),l=!1,b=0;b<h.length;b++)e=new D(""+b,p+"_"+b,h[b],l,!0),a.get_Items().push(e),k(e,h[b],p+"_"+b,m)}}}function p(a,k,m,b){var f=k.get_Items();
if(f.length!==b._183.length)m.push({property:b,value:k._277,updateMarkup:!0});else{for(var d=!1,e=0;e<f.length;e++){k=f[e];var g=b._183[e];if(k._105!==g._105){m.push({property:b,value:k._277,updateMarkup:!0});d=!0;break}}if(!d)for(e=0;e<f.length;e++)if(k=f[e],g=b._183[e],k._105!==g._105)m.push({property:g,value:g._277,updateMarkup:!0});else if(g._183.length!==k._183.length)m.push({property:g,value:g._277,updateMarkup:!0});else if(0!=k._183.length)p(a,k,m,g);else if(d=g._277,k._277!=d){g=!0;if(c.ic(k._277,
Array)&&c.ic(d,Array))if(k._277.length!=d.length)g=!1;else for(var l=0;l<k._277.length;l++){if(k._277[l]!=d[l]){g=!1;break}}else g=c.isf(k._277.equals)?k._277.equals(d):!1;g||m.push({property:k,value:d})}}}var m=R.prototype;m.get_ObjectProperties=function(){return this._148};m.setPropertyValue=function(k,c){for(var p=this._614,m=k.split("_"),b=this._148,f=-1,d=0;d<m.length;d++)for(var e=0;e<b._183.length;e++)if(b._183[e]._266===m[d]){b=b._183[e];-1==f||b._548||(f=-1);-1==f&&b._548&&(f=Math.max(d-
1,0));break}var g;if(null!=b){e=[];switch(typeof b._277){case "boolean":c="True"===c?!0:!1;break;case "number":c=parseFloat(c)}try{if(1==m.length){var l=m[0];a(p,l,c)}else if(b._548){z=p;for(p=0;p<f;p++)z=Array.isArray(z)&&!isNaN(+m[p])?z[+m[p]]:z["get_"+m[p]]();for(var n=m[f],q=z["get_"+n](),p=q,d=f+1;d<m.length-1;d++)p=isNaN(+m[d])?p["get_"+m[d]]():p[+m[d]];l=m[m.length-1];p[l]=c;a(z,n,q)}else{for(var z=p,d=0;d<m.length-1;d++)z=Array.isArray(z)&&!isNaN(+m[d])?z[+m[d]]:z["get_"+m[d]]();l=m[m.length-
1];a(z,l,c)}e=this.updatePropertyGrid(new R(this._614,"","",this._346))}catch(r){e.push(b),g=r}0===e.length&&b._277!==c&&e.push(b);return{changedProperties:e,exception:g}}};m.updatePropertyGrid=function(a){var k=[],c=[];p(this,this._148,k,a._148);if(0!=k.length)for(var m=0;m<k.length;m++)k[m].property._277=k[m].value,c.push(k[m].property);f(this._148,a._148);l(this._148,a._148);return c};this._614=b;null==d&&(d="");null==e&&(e="");null!=g&&c.ad(g,c.s);this._346=g;this._148=new D(d,e,b,!1);k(this._148,
b,e,g)},x=function(b,d,e,g){function l(a,p,m){if(c.iss(a))try{a=JSON.parse(a)}catch(b){}if(e){c.iss(a)&&(a={errorMessage:a});var h=a.responseText;"error"!==p||null!=a.errorMessage||""!==h&&null!=h||(a.errorMessage="Unknown service error OR service is unavailable.");e(a,p,m)}}function f(a,p,m){if(c.iss(a))try{a=JSON.parse(a)}catch(b){l(a,p,m);return}a.success?d&&d(a,p,m):l(a,p,m)}var a=x.prototype;a.get_ActionName=function(){return this._240};a._546=function(){return this._241};c.s(b);""===b&&c.te("Action name can not be empty.");
null!=d&&c.f(d,"Success callback must be defined as function.");null!=e&&c.f(e,"Error callback must be defined as function.");this._240=b;this._155=l;this._58=f;b=n.cloneObject(g);b.success=f;b.error=l;null==b.type&&(b.type="POST");this._241=b},M=function(b,d){var e=M.prototype;e.cre=function(c){};e.crs=function(c){};e._546=function(){var b=this._41;if(0!=b.length){for(var d=b[0]._546(),f=[],a=0;a<b.length;a++)f[a]=b[a]._241.data,f[a].requestId=a+"R";var k=this,p=function(a,p,h){if(c.iss(a))try{a=
JSON.parse(a)}catch(b){}if(c._422(a)&&a.length)for(p=0;p<a.length;p++)h=parseInt(a[p].requestId),k._41[h]._155(a[p]);else for(h=a.responseText,"error"!==p||null!=a.errorMessage||""!==h&&null!=h||(a.errorMessage="Unknown service error OR service is unavailable."),p=0;p<k._41.length;p++)k._41[p]._155(a);n.triggerEvent(k,"cre")};d.data={requestsData:f};d.success=function(a,b,h){if(c.iss(a))try{a=JSON.parse(a)}catch(f){p(a,b,h);return}for(b=0;b<a.length;b++)h=parseInt(a[b].requestId),k._41[h]._58(a[b]);
n.triggerEvent(k,"crs")};d.error=p;return d}};this._240=d;c.ac(b,x);this._41=b;delete e.cre;delete e.crs};n.extend(M,x);var r=function(b){var d=r.prototype;d.get_ServiceRoute=function(){return this._200};d.addRequest=function(b){c.c(b,x);if(0===this._406)return this.sendRequest(b);this._290.push(b)};d.sendRequests=function(){var c=[],b=this._338();if(0!=b.length)for(var d=0;d<b.length;d++)c.push(this.sendRequest(b[d]));for(d=0;d<this._290.length;d++)c.push(this.sendRequest(this._290[d]));this._290=
[];return c};d.sendRequest=function(b){c.tne()};d.bi=function(){this._406++};d.ei=function(){this._406--;0>this._406&&(this._406=0);if(0===this._406)return this.sendRequests()};d._338=function(){for(var c=[],b=0;b<this._290.length;){var d=this._290[b]._240,f=r._529[d];if(null!=f){for(var a=b,k=[];a<this._290.length;)this._290[a]._240===d?(k.push(this._290[a]),this._290.splice(a,1)):a++;c.push(new M(k,f))}else b++}return c};this._200=b;this._406=0;this._290=[]};r.defaultImageService=-1;r._529={};r.rcr=
function(b,d){c.s(b,d);""!==b&&""!==d||c.tae();null!=r._529[b]&&c.tae();r._529[b]=d};r.rcr("RenderThumbnail","RenderThumbnails");r.rcr("GetImageInfo","GetImagesInfo");var N=function(b){N.superclass.constructor.call(this,b);N.prototype.sendRequest=function(b){var e=b._546(),g=u._394,l=new XMLHttpRequest;l.open("POST",this._200+"/"+b._240,!0);c.ic(e.data,FormData)?null!=g&&e.data.append("sessionId",g):(null!=e.data?(c._422(e.data)&&null!=g&&(e.data.sessionId=g),e.data=JSON.stringify(e.data)):null!=
g&&(e.data=JSON.stringify(g)),l.setRequestHeader("Content-type","application/json"));l.onreadystatechange=function(){if(4==l.readyState)if(200==l.status){var c=JSON.parse(l.responseText);e.success(c,"success")}else e.error(l.responseText,"error")};l.onerror=function(){e.error(l.responseText,"error")};l.send(e.data);return{request:b,object:l}}};n.extend(N,r);var O=function(b){O.superclass.constructor.call(this,b);O.prototype.sendRequest=function(b){var e=b._546(),g=new XMLHttpRequest;g.open("POST",
this._200,!0);var l=u._394,f=e.data;c.ic(f,FormData)?(f.append("action",b._240),null!=l&&f.append("sessionId",l)):(f=new FormData,f.append("action",b._240),null!=e.data?(e.data.sessionId=l,f.append("requestParams",JSON.stringify(e.data))):f.append("requestParams",l));g.onreadystatechange=function(){if(4==g.readyState)if(200==g.status){var a=JSON.parse(g.responseText);e.success(a,"success")}else e.error(g.responseText,"error")};g.onerror=function(){e.error(g.responseText,"error")};g.send(f);return{request:b,
object:g}}};n.extend(O,r);var v=function(b,d,e){var g=v.prototype;g.changed=function(c){};g.get_Type=function(){return"Image"};g.get_Resolution=function(){return{x:this._204.x,y:this._204.y}};g.set_Resolution=function(b,f){var a;a=null==f?{x:b.x,y:b.y}:{x:b,y:f};c.p(a);(0>=a.x||0>=a.y)&&c.te("Resolution cannot be equal or less than 0.");var k=this._204;if(k.x!==a.x||k.y!==a.y)this._204=a,this.fce("Resolution")};g.get_InterpolationMode=function(){return this._446};g.set_InterpolationMode=function(b){b=
c.e(b,I);b.equals(this._446)||(this._446=b,this.fce("InterpolationMode"))};g.get_SmoothingMode=function(){return this._593};g.set_SmoothingMode=function(b){b=c.e(b,J);b.equals(this._593)||(this._593=b,this.fce("SmoothingMode"))};g.clone=function(){return new this.constructor(this._204,this._446,this._593)};g.equals=function(b){return c.ic(b,v)&&this.constructor===b.constructor?this._465(b):!1};g.isEmpty=function(){return this.equals(new v)};g.beginInit=function(){this._244||this._479||(this._479=
!0,this._535=this.clone())};g.endInit=function(){if(!this._244&&this._479&&(this._479=!1,null!=this._535)){var c=this.gcn(this._535);0!==c.length&&(this._535=null,this._60(c))}};g.toObject=function(){return this._287()};g.iai=function(c,b){var a=c._500._191;if(null==a)return 0;if("Pdf"===a||"Docx"===a){null==b&&(b=this.gcn(new v));if(-1!==b.indexOf("Resolution"))return 2;if(-1!==b.indexOf("InterpolationMode")||-1!==b.indexOf("SmoothingMode"))return 1}return 0};g.fce=function(b){c.iss(b)&&(b=[b]);
this._479||this._60(b)};g.gcn=function(c){var b=[];this._204.x===c._204.x&&this._204.y===c._204.y||b.push("Resolution");this._446.equals(c._446)||b.push("InterpolationMode");this._593.equals(c._593)||b.push("SmoothingMode");return b};g.gsi=function(c){return this};g._465=function(c){return this._204.x===c._204.x&&this._204.y===c._204.y&&this._446.equals(c._446)&&this._593.equals(c._593)};g._287=function(){return{resolution:this._204,interpolationMode:this._446.valueOf(),smoothingMode:this._593.valueOf()}};
g._60=function(c){n.triggerEvent(this.evm,"changed",{obj:this,properties:c});n.triggerEvent(this,"changed")};null==b&&(b={x:0,y:0});c.p(b);this._204={x:b.x,y:b.y};null==d&&(d=6);this._446=c.e(d,I);null==e&&(e=4);this._593=c.e(e,J);this._479=!1;this._535=null;this._244=!1;this.evm={};delete g.changed},H=function(b){function d(a,c){var b=f,d={obj:c.obj,properties:c.properties};b._363?b._363.push(d):b._60([d])}var e=H.prototype,g=H.superclass,l=[];c.ad(b,function(a){c.c(a,v);c.ic(a,H)&&c.te("Composite rendering settings can not contain other composite rendering settings.");
a=a.constructor;-1!==l.indexOf(a)&&c.te("Composite rendering settings can contain only unique settings.");l.push(a)});g.constructor.call(this);this._318=b;for(var f=this,a=0;a<b.length;a++)q.Shared.subscribeToEvent(b[a].evm,"changed",d);this._363=null;e.get_Settings=function(){return this._318.slice()};e.set_Resolution=function(a,b){var m;m=null==b?{x:a.x,y:a.y}:{x:a,y:b};c.p(m);var d=!1;this._479||(this.beginInit(),d=!0);this._204=m;for(var h=0;h<this._318.length;h++)this._318[h].set_Resolution(m);
d&&this.endInit()};e.set_InterpolationMode=function(a){a=c.e(a,I);var b=!1;this._479||(this.beginInit(),b=!0);this._446=a;for(var m=0;m<this._318.length;m++)this._318[m].set_InterpolationMode(a);b&&this.endInit()};e.set_SmoothingMode=function(a){a=c.e(a,J);var b=!1;this._479||(this.beginInit(),b=!0);this._593=a;for(var m=0;m<this._318.length;m++)this._318[m].set_SmoothingMode(a);b&&this.endInit()};e.beginInit=function(){if(!this._479){this._479=!0;for(var a=this._318,c=0;c<a.length;c++)a[c].beginInit(),
a[c]._244=!0}};e.endInit=function(){if(this._479){this._363=[];this._479=!1;for(var a=this._318,c=0;c<a.length;c++)a[c]._244=!1,a[c].endInit();0!=this._363.length&&this._60(this._363);this._363=null}};e.clone=function(){for(var a=[],b=this._318,m=0;m<b.length;m++)a.push(b[m].clone());a=new H(a);b=this._204;a._204={x:b.x,y:b.y};a._446=c.e(this._446,I);a._593=c.e(this._593,J);return a};e.equals=function(a){if(!g.equals.call(this,a))return!1;var c=this._318;a=a._318;if(c.length!=a.length)return!1;for(var b=
0;b<c.length;b++)if(!c[b].equals(a[b]))return!1;return!0};e.isEmpty=function(){for(var a=0;a<this._318.length;a++)if(!this._318[a].isEmpty())return!1;return!0};e.toObject=function(){for(var a=g.toObject.call(this),c=[],b=0;b<this._318.length;b++)c.push(this._318[b].toObject());a.additionalProperties=JSON.stringify({settings:c});return a};e.gcn=function(a){var c=[],b=this._318;a=a._318;for(var d=Math.min(b.length,a.length),h=0;h<d;h++)if(b[h].constructor===a[h].constructor){var f=b[h].gcn(a[h]);0<
f.length&&c.push({obj:b[h],properties:f})}else c.push({obj:b[h],properties:null});if(b.length>d)for(h=d;h<b.length;h++)c.push({obj:b[h],properties:null});return c};e.iai=function(a,c){var b=this.gsi(a);if(null==b)return 0;if(null!=c){for(var d=0;d<c.length;d++){var h=c[d],f=h.obj;if(f===b&&(c=h.properties,h=f.iai(a,c),0<h))return h}return 0}return b.iai(a)};e.gsi=function(a){var c=this._318,b=null,b=null!=a._500?a._500._191:a._191;a=null;for(var d=0;d<c.length;d++)if("Image"===c[d].get_Type()){a=
c[d];break}var h=[];if(null==a)h=c;else for(d=0;d<c.length;d++)c[d]!==a&&h.push(c[d]);if(null!==b)for(d=0;d<h.length;d++){if(h[d].get_Type()===b)return h[d]}else if(0<h.length)return h[0];return null!=a?a:h[0]}};n.extend(H,v);var P=function(c,d){var e=P.prototype;e.get_Id=function(){return this._438};e.get_Password=function(){return this._549};this._438=c;this._549=void 0==d?"":d},y=function(){var b=y.prototype;b.changed=function(c){};b.get_IsColorManagementEnabled=function(){return this._126};b.set_IsColorManagementEnabled=
function(b){c.b(b);this._126!==b&&(this._126=b,n.triggerEvent(this,"changed"),n.triggerEvent(this._119,"changed"))};b.clone=function(){var c=new this.constructor;c._126=this._126;return c};b.equals=function(b){return c.ic(b,y)?this._126===b._126:!1};b.toObject=function(){return this._287()};b._287=function(){return{isColorManagementEnabled:this._126}};this._126=!0;this._119={};delete b.changed},K=function(b,d,e){function g(c,a){null==a||a.isEmpty()||(c.renderingSettings=a.toObject())}function l(c,
a){null!=a&&(c.decodingSettings=a.toObject())}this._90=b;null==d&&(d=r.defaultImageService);-1!==d&&c.c(d,r,"You should specify correct image service OR define the default image service.");this._278=d;null==e&&(e=r.defaultAnnotationService);null!=e&&(c.c(e,r,"You should specify correct annotation service OR define the default annotation service"),this._429=e);this._549=this._191=null;b=K.prototype;b.get_ImageId=function(){return this._90};b.get_ImageService=function(){c.c(this._278,r,"Image service is not an instance of WebServiceJS class.");
return this._278};b.get_AnnotationService=function(){c.c(this._429,r,"Image annotating service is not an instance of WebServiceJS class.");return this._429};b.get_Password=function(){return this._549};b.set_Password=function(b){null!=b&&c.s(b);this._549!==b&&(this._549=b)};b.equals=function(b){if(this===b)return!0;if(!c.ic(b,K)||this._90!==b._90)return!1;var a=this._278,k=b._278,d=this._429;b=b._429;d=d===b||null!=d&&null!=b&&d._200===b._200;return(a===k||-1!==a&&-1!==k&&a._200===k._200)&&d};b._111=
function(b,a,k,d,m){c.n(b);null!=a&&c.c(a,v);null!=k&&c.c(k,y);var e={};e.imageInfo={fileInfo:{id:this._90,password:this._549},pageIndex:b};g(e,a);l(e,k);var h=this;b=new x("GetImageInfo",function(a){null==h._191&&null!=a.decoderName&&(h._191=a.decoderName);d&&d(a)},m,{data:e});return this.get_ImageService().addRequest(b)};b._390=function(b,a,k,d,m,e,h,w,t){m=c.e(m,E);c.n(b,a,k);c.b(d);null!=e&&c.c(e,v);null!=h&&c.c(h,y);var s={};s.imageInfo={fileInfo:{id:this._90,password:this._549},pageIndex:b};
s.thumbnailSize={width:a,height:k};s.imageType=m.valueOf();s.useCache=d;g(s,e);l(s,h);var n=this;b=new x("RenderThumbnail",function(a){null==n._191&&null!=a.decoderName&&(n._191=a.decoderName);w&&w(a)},t,{data:s});this.get_ImageService().addRequest(b)};b._449=function(b,a,k,d,m,e,h,w,t,s,n,C,q){t=c.e(t,E);c.n(b,a,k,d,m);c.b(h,w);c.p(e);null!=s&&c.c(s,v);null!=n&&c.c(n,y);var r={};r.imageInfo={fileInfo:{id:this._90,password:this._549},pageIndex:b};r.tileSize={width:d,height:m};r.imagePoint={x:a,y:k};
r.scale=e;r.useCache=h;r.renderNeighbourTiles=w;r.imageType=t.valueOf();g(r,s);l(r,n);b=new x("RenderImageTile",C,q,{data:r});return this.get_ImageService().sendRequest(b)};b._269=function(b,a,k,d,m,e,h,w,t){m=c.e(m,E);c.n(b,a,k);c.p(d);null!=e&&c.c(e,v);null!=h&&c.c(h,y);var s={};s.imageInfo={fileInfo:{id:this._90,password:this._549},pageIndex:b};s.tileSize={width:a,height:k};s.scale=d;s.imageType=m.valueOf();g(s,e);l(s,h);b=new x("RenderImageTiles",w,t,{data:s});return this.get_ImageService().sendRequest(b)};
b._485=function(b,a,k,d,e){c.n(b);null!=a&&c.c(a,v);null!=k&&c.c(k,y);var A={};A.imageInfo={fileInfo:{id:this._90,password:this._549},pageIndex:b};g(A,a);l(A,k);b=new x("GetImageAsBase64String",d,e,{data:A});return this.get_ImageService().sendRequest(b)}},B=function(b,d){function e(a){q.Shared.subscribeToEvent(a._564.evm,"changed."+a._368,function(c,b){var d=a._564.iai(a,b.properties);0<d&&a.ci("rsc",2===d?!0:!1);n.triggerEvent(a,"renderingSettingsChanged",void 0)})}function g(a){null!=a._381&&q.Shared.subscribeToEvent(a._381._119,
"changed."+a._368,function(){l(a,!0)})}function l(a,c){c&&a.ci("dsc",!1);n.triggerEvent(a,"decodingSettingsChanged",void 0)}var f=B.prototype;f.renderingSettingsChanged=function(a){};f.decodingSettingsChanged=function(a){};f.icd=function(a,c){};f.get_ImageId=function(){return this._500._90};f.get_Size=function(){return null==this._420||null==this._180?null:{width:this._420,height:this._180}};f.get_Resolution=function(){return null==this._328||null==this._110?null:{x:this._328,y:this._110}};f.get_PixelFormat=
function(){return this._606};f.get_Source=function(){return this._500};f.get_PageIndex=function(){return this._512};f.get_IsVector=function(){return this._356};f.get_RenderingSettings=function(){return this._564};f.set_RenderingSettings=function(a){c.c(a,v);var b=this._564;if(!this._564.equals(a)&&(q.Shared.unsubscribeFromEvent(this._564.evm,"."+this._368),this._564=a,e(this),!b.isEmpty()||!a.isEmpty())){b=b.gsi(this);a=a.gsi(this);var d=0;if(b.constructor===a.constructor)var m=a.gcn(b),d=a.iai(this,
m);else{var f=b.iai(this),h=a.iai(this);if(f!==h)d=Math.max(f,h);else if(0!==h){var f=b.gcn(new b.constructor),g=a.gcn(new a.constructor);if(f.length!==g.length)d=h;else{for(var t=!1,s=0;s<f.length;s++){var l=f[s];if(-1===g.indexOf(l)){d=h;t=!0;break}else{var C=b["get_"+l](),l=a["get_"+l]();if(c._422(C))if(c.ic(C,F)){if(!C.equals(l)){d=h;t=!0;break}}else for(m in C){if(C[m]!==l[m]){d=h;t=!0;break}}else if(C!==l){d=h;t=!0;break}}}t||(d=0)}}}0<d&&this.ci("rsc",2===d?!0:!1);n.triggerEvent(this,"renderingSettingsChanged",
void 0)}};f.get_DecodingSettings=function(){return this._381};f.set_DecodingSettings=function(a){null!=a&&c.c(a,y);if(!(null!=this._381&&this._381.equals(a)||null==this._381&&null==a)){null!=this._381&&q.Shared.unsubscribeFromEvent(this._381._119,"."+this._368);var b=this._381;this._381=a;g(this);l(this,null==b&&a._126||null==a&&b._126||null!=b&&null!=a)}};f.get_Guid=function(){return this._368};f.get_IsBad=function(){return this._574};f.get_Metadata=function(){null==q.Imaging&&c.te("'Vintasoft.Imaging' script is not found.");
null==this._169&&(this._169=new q.Imaging.WebImageMetadataJS(this));return this._169};f.get_DecoderName=function(){return this._500._191};f.equals=function(a){return this===a?!0:c.ic(a,B)?a._512===this._512&&this._500.equals(a._500):!1};f.renderTile=function(a,c,b){this._387(a,!1,c,b)};f.renderTileWithNeighbours=function(a,c,b){a.useCache=!0;this._387(a,!0,c,b)};f.renderTiles=function(a,b,d){null!=a&&c._422(a)||c.te("The tiles rendering settings cannot be empty.");var e=a.width,f=a.height,h=a.scale;
null==h&&(h={x:1,y:1});var g=a.format;null==g&&(g=new E(1));var t=a.renderingSettings;null==t&&(t=this._564);var s=a.decodingSettings;null==s&&(s=this._381);var l=this;return this._500._269(this._512,e,f,h,g,t,s,function(a){a.image=l;a.renderingSettings=t;a.decodingSettings=s;b&&b(a)},function(a){a.image=l;a.renderingSettings=t;a.decodingSettings=s;a.blocked||(l._574=!0);d&&d(a)})};f.renderThumbnail=function(a,b,d){function e(a){a.image=q;a.width=f;a.height=h;a.renderingSettings=l;a.decodingSettings=
n}null!=a&&c._422(a)||c.te("The thumbnail rendering settings cannot be empty.");var f=a.width,h=a.height,g=a.format;null==g&&(g=new E(1));var t=a.useCache;null==t&&(t=!0);var l=a.renderingSettings;null==l&&(l=this._564);var n=a.decodingSettings;null==n&&(n=this._381);var q=this;this._500._390(this._512,f,h,t,g,l,n,function(a){e(a);null!=a.imageParam&&q._499(a.imageParam);b&&b(a)},function(a){e(a);null!=a.imageParam&&q._499(a.imageParam);a.blocked||(q._574=!0);d&&d(a)})};f.getImageInfo=function(a,
c){function b(a){a.image=h;a.renderingSettings=d;null!=e&&(a.decodingSettings=e)}var d=this._564,e=this._381,h=this;return this._500._111(this._512,this._564,this._381,function(c){b(c);h._499(c);a&&a(c)},function(a){b(a);h._499(a);a.blocked||(h._574=!0);c&&c(a)})};f.getImageAsBase64String=function(a,c){function b(a){a.image=d;a.renderingSettings=e;null!=h&&(a.decodingSettings=h)}var d=this,e=this._564,h=this._381;return this._500._485(this._512,e,h,function(c){b(c);a&&a(c)},function(a){b(a);a.blocked||
(d._574=!0);c&&c(a)})};f.cto=function(){return{fileInfo:{id:this._500._90,password:this._500._549},pageIndex:this._512}};f.csto=function(){var a={},c=this._564;null==c||c.isEmpty()||c.iai(this)&&(a.renderingSettings=c.toObject());null!=this._381&&(a.decodingSettings=this._381.toObject());return a};f.gi=function(){return this._476};f.ci=function(a,c,b){null==a&&(a="dc");null==c&&(c=!0);null==b&&(b=c);this._476=u.guid();c&&(this._110=this._328=this._180=this._420=null,this._574=!1);n.triggerEvent(this.evm,
"icd",{i:this,d:a,idc:c,imc:b})};f.sm=function(a){null!=this._169&&c.te("Image already has metadata object. Use 'get_Metadata' property.");this._169=a};f._387=function(a,b,d,e){function f(a){a.image=y;a.pos={x:h,y:g};a.size={width:l,height:s};a.scale=n;a.renderingSettings=u;a.decodingSettings=v}null!=a&&c._422(a)||c.te("The tile rendering settings cannot be empty.");var h=a.x;null==h&&(h=0);var g=a.y;null==g&&(g=0);var l=a.width,s=a.height,n=a.scale;null==n&&(n={x:1,y:1});var q=a.useCache;null==q&&
(q=!0);var r=a.format;null==r&&(r=new E(1));var u=a.renderingSettings;null==u&&(u=this._564);var v=a.decodingSettings;null==v&&(v=this._381);var x=a=Infinity;null!=this._420&&0!==this._420&&0!==this._180&&(a=this._420,x=this._180);(0>h||h>=a||0>g||g>=x)&&c.te("Tile must have coordinates inside the image.");var y=this;return this._500._449(this._512,h,g,l,s,n,q,b,r,u,v,function(a){f(a);d&&d(a)},function(a){f(a);a.blocked||(y._574=!0);e&&e(a)})};f._499=function(a){if(null==this._420||null==this._180||
null==this._328||null==this._110){var c=a.imageSize,b=a.imageResolution;if(null!=c&&null!=b){this._420=+c.width;this._180=+c.height;this._328=+b.width;this._110=+b.height;this._356=a.isVector;try{this._606=new Q(a.pixelFormat)}catch(d){this._606=new Q(0)}if(0===this._420||0===this._180)this._574=!0}}a.pixelFormat=this._606};c.c(b,K);c.n(d);this._500=b;this._512=d;this._368=u.guid();this._476=u.guid();this._564=new v;e(this);this._169=this._381=null;this.evm={};this._356=this._606=this._110=this._328=
this._180=this._420=null;this._574=!1;delete f.decodingSettingsChanged;delete f.renderingSettingsChanged;delete f.icd};r.defaultImageCollectionService=-1;var S=function(){function b(a){c.c(a,r,"Image collection service is not correct.")}function d(a){for(var c=a.files,b=[],d=[],e=0;e<c.length;e++)for(var h=c[e].pageCount,f=0;f<h;f++){var g=c[e].id,l=b[g];null==l&&(l=new K(g),b[g]=l,l.set_Password(c[e].password));d.push(new B(l,f))}a.images=d}function e(a,b){var d={};c.ad(b,function(b){c.n(b);(0>b||
b>=a._6.length)&&c.toe();null==d[b]&&(d[b]=1)});var e=[],f;for(f in d)e.push(+f);return e}function g(a,b,d){var e=!1,f=!1,h=!1;for(null==d._500._429&&(h=!0);b<a.length;b++){var g=a[b],l;a:{l=g;var n=d,q=!e;if(l._500.equals(n._500)&&(l._512===n._512&&c.te("Image already exists in collection."),q)){n._500=l._500;n._500._278=l._500._278;n._500._429=l._500._429;l=!0;break a}l=!1}l&&(h=f=e=!0);f||d._500._278._200!==g._500._278._200||(d._500._278=g._500._278,f=!0);h||null==g._500._429||d._500._429._200!==
g._500._429._200||(d._500._429=g._500._429,h=!0)}}function l(a,c){for(var b=-1,d=0;d<a._6.length;d++)if(a._6[d]._368==c){b=d;break}return b}var f=S.prototype;f.changing=function(a,c){};f.changed=function(a,c){};f.get_Count=function(){return this._6.length};f.get_Image=function(a){c.n(a);if(0<=a&&a<this._6.length)return this._6[a];c.toe()};f.indexOf=function(a){c.iss(a)||c.c(a,B);a=c.iss(a)?a:a._368;return l(this,a)};f.clear=function(){if(0!==this._6.length){var a={actionName:"clear",images:this.toArray()};
this._497(a);this._6=[];this._158(a)}};f.add=function(a){this.insert(this._6.length,a)};f.addRange=function(a){this.insertRange(this._6.length,a)};f.insert=function(a,b){c.n(a);c.c(b,B);if(0<=a&&a<=this._6.length){g(this._6,0,b);var d={actionName:"insert",imageIndex:a,image:b};this._497(d);this._6.splice(a,0,b);this._158(d)}else c.toe()};f.insertRange=function(a,b){var d=!0;c.ic(b,S)&&(b=b._6,d=!1);c.n(a);d&&c.ac(b,B);if(0<=a&&a<=this._6.length){for(var e=b.length,d=b.concat(this._6),e=e-1;0<=e;e--)g(d,
e+1,b[e]);d={actionName:"insertRange",imageIndex:a,images:b};this._497(d);for(e=0;e<b.length;e++)this._6.splice(a+e,0,b[e]);this._158(d)}else c.toe()};f.removeAt=function(a){c.n(a);if(0<=a&&a<this._6.length&&0!=this._6.length){var b={actionName:"removeAt",imageIndex:a,image:this._6[a]};this._497(b);this._6.splice(a,1);this._158(b)}else c.toe()};f.remove=function(a){c.c(a,B);a=l(this,a._368);-1!==a?this.removeAt(a):c.te("Image does not exist.")};f.removeImages=function(a){var b=[],d=this;c.ad(a,function(a){c.c(a,
B);a=l(d,a._368);-1!==a?b.push(a):c.te("Image does not exist.")});this.removeRange(b)};f.removeRange=function(a){a=e(this,a);for(var c=[],b=0;b<a.length;b++)c.push(this._6[a[b]]);c={actionName:"removeRange",imagesIndexes:a,images:c};this._497(c);for(b=a.length-1;0<=b;b--)this._6.splice(a[b],1);this._158(c)};f.set=function(a,b){c.n(a);c.c(b,B);if(0<=a&&a<this._6.length&&0!=this._6.length){var d={actionName:"set",imageIndex:a,image:b,previousImage:this._6[a]};this._497(d);this._116=!1;this.removeAt(a);
this.insert(a,b);this._116=!0;this._158(d)}else c.toe()};f.toArray=function(){return this._6.slice()};f.setRenderingSettings=function(a){c.c(a,v);for(var b=0;b<this._6.length;b++)this._6[b].set_RenderingSettings(a.clone())};f.setDecodingSettings=function(a){null!=a&&c.c(a,y);if(null!=a)for(var b=0;b<this._6.length;b++)this._6[b].set_DecodingSettings(a.clone());else for(b=0;b<this._6.length;b++)this._6[b].set_DecodingSettings()};f.getImageFilesInfos=function(a,e,f,g){Array.isArray(a)||c.te("The fileIds parameter must be an array");
var l=!0;for(g=0;g<a.length;g++)c.iss(a[g])||(l=!1);if(l)for(l=[],g=0;g<a.length;g++)l.push({id:a[g],password:""});else for(l=[],g=0;g<a.length;g++)void 0==a[g].get_Id()&&c.te("File identifier is not defined"),l.push({id:a[g].get_Id(),password:a[g].get_Password()});a=l;g=r.defaultImageCollectionService;c.ic(e,r)&&(g=e);b(g);a=new x("GetImageFileInfo",function(a,b,g){d(a);c.isf(e)&&e(a,b,g)},f,{data:{fileIds:a}});return g.sendRequest(a)};f.openFile=function(a,b,d,e){c.iss(a)?a=new P(a,""):(void 0==
a.get_Id()&&c.te("File identifier is not defined"),c.iss(a.get_Id())||c.te("File identifier is not a string"));return this.openFiles([a],function(a,d,e){c.isf(b)&&b(a,d,e)},d,e)};f.openFiles=function(a,b,d,e){Array.isArray(a)||c.te("The fileIds parameter must be an array");for(var g=!0,h=0;h<a.length;h++)c.iss(a[h])||(g=!1);if(g){g=[];for(h=0;h<a.length;h++)g.push(new P(a[h],""));a=g}else for(h=0;h<a.length;h++)void 0==a[h].get_Id()&&c.te("File identifier is not defined");c.ic(b,r)&&(e=b);var f=this;
return this.getImageFilesInfos(a,function(a,d,e){f.clear();f.addRange(a.images);c.isf(b)&&b(a,d,e)},d,e)};f.saveState=function(a,c,d){null==d&&(d=r.defaultImageCollectionService);b(d);for(var e=this.toArray(),g=[],h=0;h<e.length;h++){var f=e[h].get_Source();g.push({imageId:f._90,pageIndex:e[h]._512})}a=new x("SaveState",a,c,{data:{imageInfos:g}});return d.sendRequest(a)};f.loadState=function(a,e,g){null==g&&(g=r.defaultImageCollectionService);b(g);e=new x("LoadState",function(b,e,h){d(b);c.isf(a)&&
a(b,e,h)},e,{data:{}});return g.sendRequest(e)};f._497=function(a){this._116&&(n.triggerEvent(this.evm,"changing",a),n.triggerEvent(this,"changing",a))};f._158=function(a){this._116&&(n.triggerEvent(this.evm,"changed",a),n.triggerEvent(this,"changed",a))};this._6=[];this.evm={};this._116=!0;delete f.changing;delete f.changed},T=function(){var b=T.prototype;this._450={};b.setData=function(b,e){c.s(b);null!=e?this._450[b]=e:delete this._450[b]};b.getData=function(b){c.s(b);return this._450[b]};b.clear=
function(){this._450={}};b.contains=function(b){c.s(b);return null!=this._450[b]}},U=function(){function b(a,b){var c=b.getAttribute(q);""!==c&&(c=a.getLocalizationInfo(c),null!=c&&d(b,c,a))}function d(a,c,g){var f=c.text;null!=f&&(a.innerText=f);f=c.title;null!=f&&(a.title=f);f=c.alt;null!=f&&(a.alt=f);f=c.value;null!=f&&(a.value=f);c=c.items;a=e(a);if(null!=c)for(f=0;f<a.length;f++){var k=a[f],l=k.getAttribute(q),l=c[l];null!=l&&d(k,l,g)}else for(f=0;f<a.length;f++)b(g,a[f])}function e(a){var b=
"["+q+"]";if(null==a){var c=document.querySelectorAll(b),c=Array.prototype.slice.call(c),d=[];c.forEach(function(a){0==n.getParents(a,b).length&&d.push(a)})}else c=a.querySelectorAll(b),c=Array.prototype.slice.call(c),d=[],c.forEach(function(c){for(var e=n.getParents(c,b),f=e.length-1;0<=f;)if(e[f]!==a)f--;else break;e.splice(f,e.length-f);0==e.length&&d.push(c)});return d}function g(a){a._604||c.te("Localization dictionary is not available.")}function l(a,b){var c=new XMLHttpRequest;c.overrideMimeType&&
c.overrideMimeType("text/plain");c.onreadystatechange=function(){4===c.readyState&&(200===c.status||0===c.status?b(c.responseText):p("Not found: "+a))};c.open("GET",a);c.send("")}function f(b,c){var d=a(b);a:{for(var e=0;e<c.length;e++)if(c[e]===d){d=c[e];break a}d=null}return null!=d?d:c[0]}function a(a){a=a.toLowerCase();var b=a.indexOf("-");return 0<b?a.substring(0,b):a}function k(b,c){l(c,function(d){function e(a){var c=!1;try{b._376=JSON.parse(a)}catch(d){p("Cannot parse the localization dictionary file."),
c=!0}c||(b._604=!0,n.triggerEvent(b,"ready"))}var g;try{g=JSON.parse(d)}catch(k){p("Cannot parse the localization settings file.");return}d=g.locales;if(null==d||0===d.length)p("The localization settings file does not contain information about locales.");else{for(g=0;g<d.length;g++)d[g]=a(d[g]);d=f(navigator.language||navigator.browserLanguage,d);d=c.split("/").slice(0,-1).concat(d+".txt").join("/");l(d,e)}})}function p(a){console.error?console.error(a):console.log("ERROR: "+a)}var m=U.prototype;
m.ready=function(a){};m.get_IsReady=function(){return this._604};m.getLocalizationInfo=function(a){g(this);return this._376[a]};m.localizeDocument=function(){g(this);for(var a=e(),c=0;c<a.length;c++)b(this,a[c])};var q="localizationId";this._604=!1;this._376=null;(function(a){var b=document.head.querySelector("link[rel='localization']");b?k(a,b.href):p("Localization settings are not found. Please add 'link' element to your page for specifying how to find localization settings: '<link rel='localization' href = '/locales/settings.json'>'")})(this)};
n.WebPixelFormatEnumJS=Q;n.WebInterpolationModeEnumJS=I;n.WebSmoothingModeEnumJS=J;n.WebImageTypeEnumJS=E;n.pv=c;n.WebImagingEnviromentJS=u;n.EnumGenerator=G;n.WebEnumItemBase=F;n.WebFlagsEnumItemBase=L;n.WebPropertyInfoJS=D;n.WebPropertyGridJS=R;n.WebRequestJS=x;n.WebCompositeRequestJS=M;n.WebServiceJS=r;n.WebServiceControllerJS=N;n.WebServiceHandlerJS=O;n.WebFileInfoJS=P;n.WebDecodingSettingsJS=y;n.WebRenderingSettingsJS=v;n.WebCompositeRenderingSettingsJS=H;n.WebImageSourceJS=K;n.WebImageJS=B;
n.WebImageCollectionJS=S;n.WebObjectClipboardJS=T;n.VintasoftLocalizationJS=U})(q.Shared||(q.Shared={}))})(Vintasoft||(Vintasoft={}));
